Install storybook & tailwind
SheetAble/SheetAble pull request #96
Opened 2024-11-11 18:35 UTC by CRBroughton

## Description

Installs Storybook, TailwindCSS and CVA to manage classes. I've also included a demo button component to show Tailwind properly working with Storybook.

2024-11-17 21:27 UTC, vallezw commented
There are some merge conflicts @CRBroughton

2024-11-18 19:11 UTC, CRBroughton commented
Should all be fixed and ready to merge :partying_face:

2024-11-19 20:57 UTC, vallezw requested changes
Looks good to me I removed some of the boilerplate stuff, and left a nit comment. Look it over if you have the time

2024-11-19 20:57 UTC, vallezw commented on .vscode/settings.json
> +{
Id vote for putting this file in the gitignore or is there any specific reason for including it?

2024-11-20 19:38 UTC, CRBroughton commented on .vscode/settings.json
> +{
Is required for some of the tailwind support in VSCode

2024-11-20 19:39 UTC, vallezw commented on .vscode/settings.json
> +{
Alright fair point we ll leave it in

2024-11-20 19:40 UTC, merged